# Generated by Django 5.1.6 on 2025-09-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="link",
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("django", "Django"),
                    ("js", "JavaScript"),
                    ("python", "Python"),
                ],
                default="django",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="live_demo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
